name: Build ZMK firmware with custom graphics and switched master
on: workflow_dispatch

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: custom_graphics_switch_master.yaml
      artifact_name: custom_graphics_switch_master
